// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	model "internal-transfers/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// AccountService is an autogenerated mock type for the AccountService type
type AccountService struct {
	mock.Mock
}

type AccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountService) EXPECT() *AccountService_Expecter {
	return &AccountService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, accountID, balance
func (_m *AccountService) CreateAccount(ctx context.Context, accountID int64, balance float64) error {
	ret := _m.Called(ctx, accountID, balance)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64) error); ok {
		r0 = rf(ctx, accountID, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type AccountService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
//   - balance float64
func (_e *AccountService_Expecter) CreateAccount(ctx interface{}, accountID interface{}, balance interface{}) *AccountService_CreateAccount_Call {
	return &AccountService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, accountID, balance)}
}

func (_c *AccountService_CreateAccount_Call) Run(run func(ctx context.Context, accountID int64, balance float64)) *AccountService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(float64))
	})
	return _c
}

func (_c *AccountService_CreateAccount_Call) Return(_a0 error) *AccountService_CreateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountService_CreateAccount_Call) RunAndReturn(run func(context.Context, int64, float64) error) *AccountService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, accountID
func (_m *AccountService) GetAccount(ctx context.Context, accountID int64) (*model.Account, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Account, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountService_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type AccountService_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
func (_e *AccountService_Expecter) GetAccount(ctx interface{}, accountID interface{}) *AccountService_GetAccount_Call {
	return &AccountService_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, accountID)}
}

func (_c *AccountService_GetAccount_Call) Run(run func(ctx context.Context, accountID int64)) *AccountService_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *AccountService_GetAccount_Call) Return(_a0 *model.Account, _a1 error) *AccountService_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountService_GetAccount_Call) RunAndReturn(run func(context.Context, int64) (*model.Account, error)) *AccountService_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountService creates a new instance of AccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountService {
	mock := &AccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
